error: Encode context in JSON
Having the error context in JSON instead of the obscure Python
dictionary format allows copy-pasting the output into a tool like `jq`
for pretty-printing.