error: remove the pydantic url from the validation error
This makes it a bit neater and makes it not depend on the version of
pydantic by default (as it was showing the url to the specific version).

We might want to improve the message eventually but this is a step in
the right direction.

Signed-off-by: David Caro <dcaro@wikimedia.org>